services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
      - /tmp:/tmp  # Mount /tmp for file handling
    environment:
      - PYTHONPATH=/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL_BACKEND=http://backend:8000
